merge:
  whitelist:
    # a PR must have these labels set
    labels: ["ready-to-merge"]
  method: squash
  # status checks required in addition to the ones defined in GitHub Branch Protection Rules
  required_statuses:
    - "Azure Pipelines"

  delete_after_merge: true