trigger: [master, release]

jobs:
- job: WindowsBuild
  pool:
    vmImage: windows-2019
  steps:
    - checkout: self
      lfs: true      
    - task: CmdLine@2
      inputs:
        script: 'CMakeBuild/bin/cmake.exe -G "Visual Studio 16 2019" -S "../" -B "."'        
    - task: CmdLine@2
      inputs:
        script: '--build . --target ALL_BUILD'