trigger: [master, release]

jobs:
- job: WindowsBuild
  pool:
    vmImage: windows-2019
  steps:
    - task: CMake@1
      inputs:
        cmakeArgs: 'cmake -G "Visual Studio 16 2019" -S "../" -B "."'
    - task: CMake@1
      inputs:
        cmakeArgs: '--build . --target ALL_BUILD'