trigger: [master, release]

jobs:
- job: WindowsBuild
  pool:
    vmImage: windows-2019
  steps:
    - checkout: self
      lfs: true               
    - task: CmdLine@2
      inputs:
        script: 'call "cmake" -G "Visual Studio 16 2019" -S "." -B "Build/"'
    - task: CmdLine@2
      inputs:
        script: 'call "cmake" --build "Build/"" --target ALL_BUILD -j'
    - task: CmdLine@2
      inputs:
        script: 'call "cmake" --build "Build/"" --target BuildTests -j'
    - task: CmdLine@2
      inputs:
        script: 'call "ctest" --force-new-ctest-process --output-on-failure'
        workingDirectory: 'Build/'