trigger: [master, release]

jobs:
- job: WindowsBuild
  pool:
    vmImage: windows-2019
  steps:
    - checkout: self
      lfs: true               
    - task: CmdLine@1
      inputs:
        filename: '$(Build.Repository.LocalPath)/CMakeBuild/bin/cmake.exe'
        arguments: '-G "Visual Studio 16 2019" -S "../" -B "."'
    - task: CmdLine@1
      inputs:
        filename: '$(Build.Repository.LocalPath)/CMakeBuild/bin/cmake.exe'
        arguments: '--build . --target ALL_BUILD'